"""add confidence to qa_records

Revision ID: c498e24b07c2
Revises: 8a7a72654d24
Create Date: 2026-07-03 14:51:54.590722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c498e24b07c2'
down_revision = '8a7a72654d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_records', schema=None) as batch_op:
        batch_op.drop_column('confidence')

    # ### end Alembic commands ###
